Repository jessicaserqueira/Pharus, pull requests merged in 2022-04, with the labels that each got.

#11 Feature/user projects view
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus.xcodeproj/xcshareddata/xcschemes/LoginPresenterTests.xcscheme
  Pharus.xcodeproj/xcshareddata/xcschemes/Pharus.xcscheme
  Pharus.xcodeproj/xcuserdata/victor_colen.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Pharus.xcodeproj/xcuserdata/victor_colen.xcuserdatad/xcschemes/xcschememanagement.plist
  Pharus/Assets.xcassets/Medalha.imageset/Contents.json
  Pharus/Assets.xcassets/Medalha.imageset/Medalha.png
  Pharus/Assets.xcassets/Medalha.imageset/Medalha@2x.png
  Pharus/Assets.xcassets/Medalha.imageset/Medalha@3x.png
  Pharus/Assets.xcassets/Progress.imageset/Contents.json
  Pharus/Assets.xcassets/Progress.imageset/Progress.png
  Pharus/Assets.xcassets/Progress.imageset/Progress@2x.png
  Pharus/Assets.xcassets/Progress.imageset/Progress@3x.png
  Pharus/Assets.xcassets/backButtonImage.imageset/Contents.json
  Pharus/Assets.xcassets/backButtonImage.imageset/Vector.svg
  Pharus/Assets.xcassets/backButtonImage.imageset/Vector@2x.svg
  Pharus/Assets.xcassets/backButtonImage.imageset/Vector@3x.svg
  Pharus/Assets.xcassets/havaianas.imageset/Contents.json
  Pharus/Assets.xcassets/havaianas.imageset/logo-havaianas-256 1.png
  Pharus/Assets.xcassets/havaianas.imageset/logo-havaianas-256 1@2x.png
  Pharus/Assets.xcassets/havaianas.imageset/logo-havaianas-256 1@3x.png
  Pharus/Assets.xcassets/hourglass.imageset/Contents.json
  Pharus/Assets.xcassets/hourglass.imageset/SCHEDULE 1.png
  Pharus/Assets.xcassets/hourglass.imageset/SCHEDULE 1@2x.png
  Pharus/Assets.xcassets/hourglass.imageset/SCHEDULE 1@3x.png
  Pharus/Assets.xcassets/inspiration.imageset/Contents.json
  Pharus/Assets.xcassets/inspiration.imageset/INSPIRATION 1.png
  Pharus/Assets.xcassets/inspiration.imageset/INSPIRATION 1@2x.png
  Pharus/Assets.xcassets/inspiration.imageset/INSPIRATION 1@3x.png
  Pharus/Assets.xcassets/userPicture.imageset/Contents.json
  Pharus/Assets.xcassets/userPicture.imageset/girl happy drinking coffe flat illustration 2.png
  Pharus/CGFloat+Extension.swift
  Pharus/Coordinator/LoginCoodinator.swift
  Pharus/Coordinator/Service/Constants.swift
  Pharus/Coordinator/StartCoordinator.swift
  Pharus/Coordinator/UserProjectsCoordinator.swift
  Pharus/Date+Extension.swift
  Pharus/LoginPresenter.swift
  Pharus/Model/Student.json
  Pharus/Model/Student.swift
  Pharus/UIColor+Extension.swift
  Pharus/UIImageView+Extension.swift
  Pharus/UserProjectsPresenter.swift
  Pharus/View/CircleView.swift
  Pharus/View/LoginView.swift
  Pharus/View/UserProjectCell.swift
  Pharus/View/ViewController/StartViewController.swift
  Pharus/View/ViewController/UserProjectsViewController.swift
Labels: enhancement

#15 Chore/refactor
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus.xcodeproj/xcshareddata/xcschemes/LoginPresenterTests.xcscheme
  Pharus.xcodeproj/xcuserdata/victor_colen.xcuserdatad/xcschemes/xcschememanagement.plist
  Pharus/Bundle+Extension.swift
  Pharus/Coordinator/Service/Constants.swift
  Pharus/Date+Extension.swift
  Pharus/UIView+Extension.swift
  Pharus/View/CircleProgressView.swift
  Pharus/View/UserProjectCell.swift
  Pharus/View/ViewController/UserProjectsViewController.swift
  PharusTests/LoginPresenterTests.swift
Labels: refactor, grunt

#18 Feature/user projects ranking
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Assets.xcassets/medal.imageset/Contents.json
  Pharus/Assets.xcassets/medal.imageset/Medalha.png
  Pharus/Assets.xcassets/medal.imageset/Medalha@2x.png
  Pharus/Assets.xcassets/medal.imageset/Medalha@3x.png
  Pharus/Assets.xcassets/thirdPlace.imageset/3_3 1.png
  Pharus/Assets.xcassets/thirdPlace.imageset/3_3 1@2x.png
  Pharus/Assets.xcassets/thirdPlace.imageset/3_3 1@3x.png
  Pharus/Assets.xcassets/thirdPlace.imageset/Contents.json
  Pharus/Coordinator/Service/Constants.swift
  Pharus/UIColor+Extension.swift
  Pharus/View/UserProjectRankingCell.swift
  Pharus/View/ViewController/UserProjectsRankingViewController.swift
Labels: enhancement, grunt

#19 chore: remove unused date extension functions
  Pharus/Date+Extension.swift
Labels: grunt

#33 Refactor/refactor scenes
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Coordinator/TabBarCoordinator.swift
  Pharus/Scenes/Alert/AlertCoordinator.swift
  Pharus/Scenes/Alert/AlertPresenter.swift
  Pharus/Scenes/Alert/AlertView.swift
  Pharus/Scenes/Alert/AlertViewController.swift
  Pharus/Scenes/Login/LoginCoodinator.swift
  Pharus/Scenes/Login/LoginPresenter.swift
  Pharus/Scenes/Login/LoginView.swift
  Pharus/Scenes/Login/LoginViewController.swift
  Pharus/Scenes/Project Sheet/ProjectSheetView.swift
  Pharus/Scenes/Project Sheet/ProjectSheetViewController.swift
  Pharus/Scenes/Send File/SendFileCoordinator.swift
  Pharus/Scenes/Send File/SendFilePresenter.swift
  Pharus/Scenes/Send File/SendFileView.swift
  Pharus/Scenes/Send File/SendFileViewController.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailCoordinator.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailPresenter.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailViewController.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectRankingCell.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectsRankingCoordinator.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectsRankingPresenter.swift.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectsRankingViewController.swift
  Pharus/Scenes/Student Projects Ranking/UserProjectsRankingCoordinator.swift
  Pharus/Scenes/Student Projects/StudentProjectCell.swift
  Pharus/Scenes/Student Projects/StudentProjectsCoordinator.swift
  Pharus/Scenes/Student Projects/StudentProjectsPresenter.swift
  Pharus/Scenes/Student Projects/StudentProjectsViewController.swift
Labels: refactor, grunt

#35 create profile screen
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/apagar.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Assets.xcassets/Icons/logoutButtonIcon.imageset/Contents.json
  Pharus/Assets.xcassets/Icons/logoutButtonIcon.imageset/logoutButtonIcon@1x.svg
  Pharus/Assets.xcassets/Icons/logoutButtonIcon.imageset/logoutButtonIcon@2x.svg
  Pharus/Assets.xcassets/Icons/logoutButtonIcon.imageset/logoutButtonIcon@3x.svg
  Pharus/Assets.xcassets/Images/Avatars/userImage.imageset/girl happy drinking coffe flat illustration 2.png
  Pharus/Assets.xcassets/Images/userImage.imageset/Contents.json
  Pharus/Assets.xcassets/Images/userImage.imageset/userImage@1x.png
  Pharus/Assets.xcassets/Images/userImage.imageset/userImage@2x.png
  Pharus/Assets.xcassets/Images/userImage.imageset/userImage@3x.png
  Pharus/Components/CheckmarkButton.swift
  Pharus/Components/MainCardButton.swift
  Pharus/Components/ProjectTaskView.swift
  Pharus/Coordinator/Service/Constants.swift
  Pharus/Scenes/Alert/AlertView.swift
  Pharus/Scenes/Avatar Selection/StudentAvatarView.swift
  Pharus/Scenes/Login/LoginCoodinator.swift
  Pharus/Scenes/Login/LoginView.swift
  Pharus/Scenes/Project Sheet/ProjectSheetView.swift
  Pharus/Scenes/Send File/SendFileCoordinator.swift
  Pharus/Scenes/Send File/SendFileView.swift
  Pharus/Scenes/Student Profile/StudentProfileCoordinator.swift
  Pharus/Scenes/Student Profile/StudentProfilePresenter.swift
  Pharus/Scenes/Student Profile/StudentProfileViewController.swift
  Pharus/Scenes/Student Profile/StudenteProfileView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailViewController.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectRankingCell.swift
  Pharus/Scenes/Student Projects/StudentProjectCell.swift
Labels: enhancement

#36 Feature/tabbar navigation
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Components/HomeMiniCardView.swift
  Pharus/Components/HomeNewsView.swift
  Pharus/Components/StudentProfileButton.swift
  Pharus/Coordinator/TabBarCoordinator.swift
  Pharus/Scenes/Avatar Selection/StudentAvatarViewController.swift
  Pharus/Scenes/Login/LoginCoodinator.swift
  Pharus/Scenes/Student Home/StudentHomeCoordinator.swift
  Pharus/Scenes/Student Home/StudentHomePresenter.swift
  Pharus/Scenes/Student Home/StudentHomeView.swift
  Pharus/Scenes/Student Home/StudentHomeViewController.swift
  Pharus/Scenes/Student Profile/StudentProfileCoordinator.swift
  Pharus/Scenes/Student Profile/StudentProfilePresenter.swift
  Pharus/Scenes/Student Profile/StudentProfileViewController.swift
  Pharus/Scenes/Student Profile/StudenteProfileView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailViewController.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectsRankingViewController.swift
  Pharus/Scenes/Student Projects/StudentProjectsViewController.swift
  Pharus/SystemDelegate/AppDelegate.swift
Labels: enhancement, grunt

#41 feat: add disabled colors to student view, add new colors to sendFile…
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Assets.xcassets/Icons/checkIcon.imageset/$icon-check.svg
  Pharus/Assets.xcassets/Icons/checkIcon.imageset/$icon-check@2x.svg
  Pharus/Assets.xcassets/Icons/checkIcon.imageset/$icon-check@3x.svg
  Pharus/Assets.xcassets/Icons/checkIcon.imageset/Contents.json
  Pharus/Assets.xcassets/Icons/uploadIcon.imageset/$icon-upload.svg
  Pharus/Assets.xcassets/Icons/uploadIcon.imageset/$icon-upload@2x.svg
  Pharus/Assets.xcassets/Icons/uploadIcon.imageset/$icon-upload@3x.svg
  Pharus/Assets.xcassets/Icons/uploadIcon.imageset/Contents.json
  Pharus/Assets.xcassets/Images/checkImage.imageset/alterIcon.pdf
  Pharus/Assets.xcassets/Images/uploadImage.imageset/upload.pdf
  Pharus/Assets.xcassets/Images/uploadImage.imageset/upload@2x.png
  Pharus/Assets.xcassets/Images/uploadImage.imageset/upload@3x.png
  Pharus/Components/MainCardButton.swift
  Pharus/Components/ProjectScheduleView.swift
  Pharus/Coordinator/Service/Constants.swift
  Pharus/Scenes/Alert/AlertView.swift
  Pharus/Scenes/Login/LoginView.swift
  Pharus/Scenes/Project Sheet/ProjectSheetView.swift
  Pharus/Scenes/Send File/SendFileCoordinator.swift
  Pharus/Scenes/Send File/SendFileView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailView.swift
  Pharus/UIColor+Extension.swift
  Pharus/UIImage+Extension.swift
Labels: enhancement

#42 create home screen + resolve conflicts
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/apagar.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Assets.xcassets/Images/Avatars/rectangleImage.imageset/Contents.json
  Pharus/Assets.xcassets/Images/Avatars/rectangleImage.imageset/rectangleImage@1x.png
  Pharus/Assets.xcassets/Images/Avatars/rectangleImage.imageset/rectangleImage@2x.png
  Pharus/Assets.xcassets/Images/Avatars/rectangleImage.imageset/rectangleImage@3x.png
  Pharus/Components/HomeNewsView.swift
  Pharus/Coordinator/Service/Constants.swift
  Pharus/Coordinator/TabBarCoordinator.swift
  Pharus/Scenes/Student Home/StudentHomeView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailView.swift
  Pharus/Scenes/Student Projects/StudentProjectCell.swift
  Pharus/UIImage+Extension.swift
Labels: enhancement, refactor

#45 Feature/high fidelity student profile
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Assets.xcassets/Icons/backArrowIcon.imageset/Contents.json
  Pharus/Assets.xcassets/Icons/backArrowIcon.imageset/Group.svg
  Pharus/Assets.xcassets/Icons/backArrowIcon.imageset/Group@2x.svg
  Pharus/Assets.xcassets/Icons/backArrowIcon.imageset/Group@3x.svg
  Pharus/Assets.xcassets/Icons/logoutIcon.imageset/Contents.json
  Pharus/Assets.xcassets/Icons/logoutIcon.imageset/logoutButtonIcon@1x.svg
  Pharus/Assets.xcassets/Icons/logoutIcon.imageset/logoutButtonIcon@2x.svg
  Pharus/Assets.xcassets/Icons/logoutIcon.imageset/logoutButtonIcon@3x.svg
  Pharus/Assets.xcassets/Images/userImage.imageset/Contents.json
  Pharus/Assets.xcassets/Images/userImage.imageset/userImage@1x.png
  Pharus/Assets.xcassets/Images/userImage.imageset/userImage@2x.png
  Pharus/Assets.xcassets/Images/userImage.imageset/userImage@3x.png
  Pharus/Coordinator/Service/Constants.swift
  Pharus/Coordinator/TabBarCoordinator.swift
  Pharus/Model/Student.json
  Pharus/Model/Student.swift
  Pharus/Scenes/Student Home/StudentHomeViewController.swift
  Pharus/Scenes/Student Profile/StudentProfileCoordinator.swift
  Pharus/Scenes/Student Profile/StudentProfileViewController.swift
  Pharus/Scenes/Student Profile/StudenteProfileView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailViewController.swift
  Pharus/UIImage+Extension.swift
Labels: enhancement, refactor

#46 Api request
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/apagar.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Components/UploadMessageButton.swift
  Pharus/Info.plist
  Pharus/Pharus.entitlements
  Pharus/Scenes/Project Sheet/ProjectSheetViewController.swift
  Pharus/Scenes/Send File/SendFileCoordinator.swift
  Pharus/Scenes/Send File/SendFilePresenter.swift
  Pharus/Scenes/Send File/SendFileView.swift
  Pharus/Scenes/Send File/SendFileViewController.swift
Labels: refactor

#48 Bugfix/project details
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Assets.xcassets/Icons/rightArrowIcon.imageset/$icon-left-arrow.svg
  Pharus/Assets.xcassets/Icons/rightArrowIcon.imageset/$icon-left-arrow@2x.svg
  Pharus/Assets.xcassets/Icons/rightArrowIcon.imageset/$icon-left-arrow@3x.svg
  Pharus/Assets.xcassets/Icons/rightArrowIcon.imageset/Contents.json
  Pharus/Components/ProjectTaskView.swift
  Pharus/Coordinator/Service/Constants.swift
  Pharus/Model/Medals.swift
  Pharus/Model/Student.swift
  Pharus/Model/Task.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailCoordinator.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailPresenter.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailViewController.swift
  Pharus/UIImage+Extension.swift
Labels: enhancement, grunt

#50 refactor
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Components/ProjectScheduleView.swift
  Pharus/Components/ProjectTaskView.swift
  Pharus/Coordinator/TabBarCoordinator.swift
  Pharus/Model/Project.swift
  Pharus/Model/ProjectModel.swift
  Pharus/Model/Student.swift
  Pharus/Model/StudentModel.swift
  Pharus/Model/Task.swift
  Pharus/Model/TaskModel.swift
  Pharus/Scenes/Alerts/Two Big Buttons Alert/TwoBigButtonsAlertCoordinator.swift
  Pharus/Scenes/Avatar Selection/AvatarSelectionCoordinator.swift
  Pharus/Scenes/Avatar Selection/AvatarSelectionViewController.swift
  Pharus/Scenes/Login/LoginCoodinator.swift
  Pharus/Scenes/Login/LoginPresenter.swift
  Pharus/Scenes/Send File/SendFileCoordinator.swift
  Pharus/Scenes/Student Home/StudentHomeCoordinator.swift
  Pharus/Scenes/Student Home/StudentHomeViewController.swift
  Pharus/Scenes/Student Profile/StudentProfileCoordinator.swift
  Pharus/Scenes/Student Profile/StudentProfileViewController.swift
  Pharus/Scenes/Student Profile/StudenteProfileView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailCoordinator.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailPresenter.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailViewController.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectRankingCell.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectsRankingCoordinator.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectsRankingViewController.swift
  Pharus/Scenes/Student Projects/StudentProjectCell.swift
  Pharus/Scenes/Student Projects/StudentProjectsCoordinator.swift
  Pharus/Scenes/Student Projects/StudentProjectsPresenter.swift
  Pharus/Scenes/Student Projects/StudentProjectsViewController.swift
Labels: refactor

#51 Feature/screen change password
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/apagar.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Components/HomeMiniCardView.swift
  Pharus/Components/SmallAlertButton.swift
  Pharus/Scenes/Alerts/Logout Alert/LogoutAlertView.swift
  Pharus/Scenes/Change Password/ChangePasswordCoordinator.swift
  Pharus/Scenes/Change Password/ChangePasswordPresenter.swift
  Pharus/Scenes/Change Password/ChangePasswordView.swift
  Pharus/Scenes/Change Password/ChangePasswordViewController.swift
  Pharus/Scenes/Login/LoginCoodinator.swift
  Pharus/Scenes/Login/LoginPresenter.swift
  Pharus/Scenes/Login/LoginView.swift
  Pharus/Scenes/Login/LoginViewController.swift
  Pharus/Scenes/Send File/SendFileViewController.swift
  Pharus/Scenes/Student Home/StudentHomeView.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectRankingCell.swift
  Pharus/UIImage+Extension.swift
Labels: enhancement

#52 Feature/student home
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Assets.xcassets/Icons/companyIcon.imageset/Contents.json
  Pharus/Assets.xcassets/Icons/companyIcon.imageset/Property 1=lg-standard.svg
  Pharus/Assets.xcassets/Icons/companyIcon.imageset/Property 1=lg-standard@2x.svg
  Pharus/Assets.xcassets/Icons/companyIcon.imageset/Property 1=lg-standard@3x.svg
  Pharus/Assets.xcassets/Icons/medalIcon.imageset/$icon-medal.svg
  Pharus/Assets.xcassets/Icons/medalIcon.imageset/$icon-medal@2x.svg
  Pharus/Assets.xcassets/Icons/medalIcon.imageset/$icon-medal@3x.svg
  Pharus/Assets.xcassets/Icons/medalIcon.imageset/Contents.json
  Pharus/Assets.xcassets/Icons/warningIcon.imageset/$icon-alert.svg
  Pharus/Assets.xcassets/Icons/warningIcon.imageset/$icon-alert@2x.svg
  Pharus/Assets.xcassets/Icons/warningIcon.imageset/$icon-alert@3x.svg
  Pharus/Assets.xcassets/Icons/warningIcon.imageset/Contents.json
  Pharus/Assets.xcassets/Images/thirdPlaceImage.imageset/3_3 1.png
  Pharus/Assets.xcassets/Images/thirdPlaceImage.imageset/3_3 1@2x.png
  Pharus/Assets.xcassets/Images/thirdPlaceImage.imageset/3_3 1@3x.png
  Pharus/Components/HomeMiniCardView.swift
  Pharus/Controller/TabBarViewController.swift
  Pharus/Coordinator/Service/Constants.swift
  Pharus/Scenes/Alerts/Confirmation Alert/ConfirmationAlertCoordinator.swift
  Pharus/Scenes/Alerts/Confirmation Alert/ConfirmationAlertPresenter.swift
  Pharus/Scenes/Alerts/Confirmation Alert/ConfirmationAlertView.swift
  Pharus/Scenes/Alerts/Confirmation Alert/ConfirmationAlertViewController.swift
  Pharus/Scenes/Alerts/One Button Alert/OneButtonAlertPresenter.swift
  Pharus/Scenes/Alerts/Project Subcription Alert/ProjectSubcriptionAlertCoordinator.swift
  Pharus/Scenes/Alerts/Project Subcription Alert/ProjectSubcriptionAlertPresenter.swift
  Pharus/Scenes/Alerts/Project Subcription Alert/ProjectSubcriptionAlertView.swift
  Pharus/Scenes/Alerts/Project Subcription Alert/ProjectSubcriptionAlertViewController.swift
  Pharus/Scenes/Change Password/ChangePasswordCoordinator.swift
  Pharus/Scenes/Change Password/ChangePasswordView.swift
  Pharus/Scenes/Send File/SendFileCoordinator.swift
  Pharus/Scenes/Send File/SendFileViewController.swift
  Pharus/Scenes/Student Home News/HomeNewsView.swift
  Pharus/Scenes/Student Home News/HomeNewsViewController.swift
  Pharus/Scenes/Student Home/StudentHomeView.swift
  Pharus/Scenes/Student Home/StudentHomeViewController.swift
  Pharus/Scenes/Student Projects/StudentProjectsCoordinator.swift
  Pharus/UIImage+Extension.swift
Labels: enhancement, refactor

#54 Feature/logout
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Model/Student.json
  Pharus/Scenes/Alerts/Confirmation Alert/ConfirmationAlertView.swift
  Pharus/Scenes/Alerts/Logout Alert/LogoutAlertCoordinator.swift
  Pharus/Scenes/Alerts/Logout Alert/LogoutAlertPresenter.swift
  Pharus/Scenes/Alerts/Logout Alert/LogoutAlertView.swift
  Pharus/Scenes/Alerts/Logout Alert/LogoutAlertViewController.swift
  Pharus/Scenes/Alerts/Project Subcription Alert/ProjectSubcriptionAlertCoordinator.swift
  Pharus/Scenes/Change Password/ChangePasswordCoordinator.swift
  Pharus/Scenes/Login/LoginCoodinator.swift
  Pharus/Scenes/Login/LoginPresenter.swift
  Pharus/Scenes/Login/LoginViewController.swift
  Pharus/Scenes/Send File/SendFileCoordinator.swift
  Pharus/Scenes/Student Profile/StudenteProfileView.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectRankingCell.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectsRankingPresenter.swift.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectsRankingViewController.swift
  Pharus/Scenes/TabBar/TabBarCoordinator.swift
  Pharus/Scenes/TabBar/TabBarViewController.swift
  Pharus/TarBarPresenter.swift
Labels: enhancement, refactor

#55 refector dark mode
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/apagar.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Components/HomeMiniCardView.swift
  Pharus/Scenes/Alerts/Confirmation Alert/ConfirmationAlertView.swift
  Pharus/Scenes/Alerts/Logout Alert/LogoutAlertView.swift
  Pharus/Scenes/Alerts/Project Subcription Alert/ProjectSubcriptionAlertView.swift
  Pharus/Scenes/Change Password/ChangePasswordView.swift
  Pharus/Scenes/Login/LoginView.swift
  Pharus/Scenes/Project Sheet/ProjectSheetView.swift
  Pharus/Scenes/Send File/SendFileView.swift
  Pharus/Scenes/Student Home News/HomeNewsView.swift
  Pharus/Scenes/Student Profile/StudentProfileViewController.swift
  Pharus/Scenes/Student Profile/StudenteProfileView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailView.swift
  Pharus/Scenes/Student Projects/StudentProjectCell.swift
  Pharus/Scenes/TabBar/TabBarCoordinator.swift
  Pharus/SystemDelegate/SceneDelegate.swift
Labels: refactor

#56 refector fonts
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/apagar.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Components/HomeMiniCardView.swift
  Pharus/Scenes/Project Sheet/ProjectSheetView.swift
  Pharus/Scenes/Send File/SendFileView.swift
  Pharus/Scenes/Student Home News/HomeNewsView.swift
  Pharus/Scenes/Student Home/StudentHomeView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailView.swift
Labels: refactor

#59 refactor login keyboard
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/apagar.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Scenes/Login/LoginView.swift
  Pharus/Scenes/Login/LoginViewController.swift
Labels: refactor

#61 refactor spacing views
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/apagar.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Scenes/Change Password/ChangePasswordView.swift
  Pharus/Scenes/Project Sheet/ProjectSheetView.swift
  Pharus/Scenes/Send File/SendFileView.swift
  Pharus/Scenes/Student Home News/HomeNewsView.swift
  Pharus/Scenes/Student Home/StudentHomeView.swift
  Pharus/Scenes/Student Profile/StudenteProfileView.swift
  Pharus/Scenes/Student Project Detail/StudentProjectDetailView.swift
  Pharus/Scenes/Student Projects Ranking/StudentProjectRankingCell.swift
  Pharus/Scenes/Student Projects/StudentProjectCell.swift
Labels: refactor

#62 refactor gradient Background
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/apagar.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/UIViewController+Extension.swift
Labels: refactor

#65 chore: minor changes
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Scenes/Alerts/Project Subcription Alert/ProjectSubcriptionAlertCoordinator.swift
  Pharus/Scenes/Alerts/Single Button Alert/SingleButtonAlertCoordinator.swift
  Pharus/Scenes/Alerts/Single Button Alert/SingleButtonAlertPresenter.swift
  Pharus/Scenes/Alerts/Single Button Alert/SingleButtonAlertView.swift
  Pharus/Scenes/Alerts/Single Button Alert/SingleButtonAlertViewController.swift
  Pharus/Scenes/Change Password/ChangePasswordCoordinator.swift
  Pharus/Scenes/Change Password/ChangePasswordPresenter.swift
  Pharus/Scenes/Change Password/ChangePasswordView.swift
  Pharus/Scenes/Change Password/ChangePasswordViewController.swift
  Pharus/Scenes/Login/LoginCoodinator.swift
  Pharus/Scenes/Login/LoginPresenter.swift
  Pharus/Scenes/Login/LoginView.swift
  Pharus/Scenes/Login/LoginViewController.swift
  Pharus/Scenes/Send File/SendFileCoordinator.swift
Labels: enhancement, refactor

#67 fix warning
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/apagar.xcuserdatad/UserInterfaceState.xcuserstate
Labels: refactor

#68 v 1.0
  Pharus.xcodeproj/project.pbxproj
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/apagar.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus.xcodeproj/project.xcworkspace/xcuserdata/victor_colen.xcuserdatad/UserInterfaceState.xcuserstate
  Pharus/Scenes/Alerts/Project Subcription Alert/ProjectSubcriptionAlertCoordinator.swift
  Pharus/Scenes/Alerts/Single Button Alert/SingleButtonAlertCoordinator.swift
  Pharus/Scenes/Alerts/Single Button Alert/SingleButtonAlertPresenter.swift
  Pharus/Scenes/Alerts/Single Button Alert/SingleButtonAlertView.swift
  Pharus/Scenes/Alerts/Single Button Alert/SingleButtonAlertViewController.swift
  Pharus/Scenes/Change Password/ChangePasswordCoordinator.swift
  Pharus/Scenes/Change Password/ChangePasswordPresenter.swift
  Pharus/Scenes/Change Password/ChangePasswordView.swift
  Pharus/Scenes/Change Password/ChangePasswordViewController.swift
  Pharus/Scenes/Login/LoginCoodinator.swift
  Pharus/Scenes/Login/LoginPresenter.swift
  Pharus/Scenes/Login/LoginView.swift
  Pharus/Scenes/Login/LoginViewController.swift
  Pharus/Scenes/Send File/SendFileCoordinator.swift
  Pharus/Scenes/Send File/SendFileView.swift
  Pharus/Scenes/Send File/SendFileViewController.swift
Labels: enhancement, refactor, grunt
